version: '3'
services:
  web:
    build: .
    volumes:
    -  ./:/usr/app
    - /usr/app/node_modules
    ports:
    - 8000:8000
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: test
      POSTGRES_PASSWORD: password

